version: '3'

services:
  api:
    container_name: shorten_url_app
    restart: always
    build:
      context: ./
    environment:
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=Khanh2001
      - DATABASE_HOST=shorten-url.chj03sgjucx0.ap-southeast-1.rds.amazonaws.com
      - DATABASE_NAME=shorten_url
      - DATABASE_PORT=3306
    ports:
      - "80:3000"
